version: "3"

services:
  webserver:
    build: .
    container_name: "petfeliz-webserver"
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./public:/usr/share/nginx/html/
      # - ./health-check.conf/:/etc/nginx/conf.d/health-check.conf
